### ISSUE TITLE
 Document workaround for Docusaurus <v2.0.0-beta9 and Node v17 in the README

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-network/docs#126]
In regards of the docs app. I get an error when running "yarn run start":
```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/home/vagrant/docs-app/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/vagrant/docs-app/node_modules/webpack/lib/util/createHash.js:46:50)
    at OriginalSource.updateHash (/home/vagrant/docs-app/node_modules/webpack/node_modules/webpack-sources/lib/OriginalSource.js:138:8)
    at NormalModule._initBuildHash (/home/vagrant/docs-app/node_modules/webpack/lib/NormalModule.js:870:17)
    at handleParseResult (/home/vagrant/docs-app/node_modules/webpack/lib/NormalModule.js:936:10)
    at /home/vagrant/docs-app/node_modules/webpack/lib/NormalModule.js:1028:4
    at processResult (/home/vagrant/docs-app/node_modules/webpack/lib/NormalModule.js:745:11)
    at /home/vagrant/docs-app/node_modules/webpack/lib/NormalModule.js:809:5
    at /home/vagrant/docs-app/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/home/vagrant/docs-app/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at Array.<anonymous> (/home/vagrant/docs-app/node_modules/loader-runner/lib/LoaderRunner.js:223:4)
    at runCallbacks (/home/vagrant/docs-app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
    at /home/vagrant/docs-app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:200:4
    at /home/vagrant/docs-app/node_modules/graceful-fs/graceful-fs.js:123:16 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.1.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
This is a known issue on Docusaurus side https://github.com/facebook/docusaurus/issues/5778 which has been closed. It is related to Node v17 support (Which I am running on my lab vm).
I have solved it using one of the recommended options:
`export NODE_OPTIONS=--openssl-legacy-provider
`I think the readme should be updated to include instructions about how to fix this error if it presents.
This can also be solved by updating Docusaurus to the latest version https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.9 where the feature https://github.com/facebook/docusaurus/pull/5814 which fixes this bug is released.

**Comment by ipopescu** [comment]
Addressed with PR 129.
