### ISSUE TITLE
Yarn run start fails

### ISSUE THREAD

**Issue by ipopescu** [casper-network/docs#184]
We see a failure when trying to run` yarn run start` to run the project (see below). There is a workaround also listed below, but it may not be good to use it for security reasons. Note version is:  17.0.1.
Please review and let us know if you can find a solution.

**Error log:**
```
ℹ ｢wds｣: Project is running at http://localhost:3000/
ℹ ｢wds｣: webpack output is served from /docs/
ℹ ｢wds｣: Content not from webpack is served from /home/fraser/Rust/docs
ℹ ｢wds｣: 404s will fallback to /index.html
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/home/fraser/Rust/docs/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/fraser/Rust/docs/node_modules/webpack/lib/util/createHash.js:46:50)
    at OriginalSource.updateHash (/home/fraser/Rust/docs/node_modules/webpack/node_modules/webpack-sources/lib/OriginalSource.js:138:8)
    at NormalModule._initBuildHash (/home/fraser/Rust/docs/node_modules/webpack/lib/NormalModule.js:870:17)
    at handleParseResult (/home/fraser/Rust/docs/node_modules/webpack/lib/NormalModule.js:936:10)
    at /home/fraser/Rust/docs/node_modules/webpack/lib/NormalModule.js:1028:4
    at processResult (/home/fraser/Rust/docs/node_modules/webpack/lib/NormalModule.js:745:11)
    at /home/fraser/Rust/docs/node_modules/webpack/lib/NormalModule.js:809:5
    at /home/fraser/Rust/docs/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/home/fraser/Rust/docs/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at Array.<anonymous> (/home/fraser/Rust/docs/node_modules/loader-runner/lib/LoaderRunner.js:223:4)
    at runCallbacks (/home/fraser/Rust/docs/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
    at /home/fraser/Rust/docs/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:200:4
    at /home/fraser/Rust/docs/node_modules/graceful-fs/graceful-fs.js:123:16 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
error Command failed with exit code 1.
```

**Workaround**:
`export NODE_OPTIONS=--openssl-legacy-provider`
The workaround is from https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported.

**Comment by ipopescu** [comment]
CC: @Fraser999. I will work with Ditoy or Luca to investigate this.

**Comment by ipopescu** [comment]
@sd-ditoy was able to fix this error.
