### ISSUE TITLE
'tokio-runtime-worker' panics at 'error binding when port is already in use

### ISSUE THREAD

**Issue by hectoratcasper** [casper-network/docs#563]
When starting, the event-sidecar app should quit when the required ports are already in used. - 

There will only be one instance of the event-sidecar per server.

**Current output:**
```
RUST_BACKTRACE=1 cargo run --release

    Finished release [optimized] target(s) in 0.11s
     Running `target/release/casper-event-sidecar`
2022-06-23T20:48:25.319862Z  INFO casper_event_sidecar: Configuration loaded
2022-06-23T20:48:25.647241Z  INFO casper_event_sidecar: Connecting to SSE network="Testnet" api_version="1.4.6" node_ip_address="159.65.118.250"
2022-06-23T20:48:25.647633Z  INFO casper_event_sidecar::rest_server: REST server starting port=3030
thread 'tokio-runtime-worker' panicked at 'error binding to 127.0.0.1:3030: error creating server listener: Address already in use (os error 98)', /home/marcetux/.cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.3.2/src/server.rs:213:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: warp::server::Server<F>::bind_ephemeral
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
   5: tokio::runtime::task::harness::poll_future
   6: tokio::runtime::task::harness::Harness<T,S>::poll
   7: std::thread::local::LocalKey<T>::with
   8: tokio::runtime::thread_pool::worker::Context::run_task
   9: tokio::runtime::thread_pool::worker::Context::run
  10: tokio::macros::scoped_tls::ScopedKey<T>::set
  11: tokio::runtime::thread_pool::worker::run
  12: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  13: tokio::runtime::task::harness::Harness<T,S>::poll
  14: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by devendran-m** [comment]
Closing this in favour of https://github.com/CasperLabs/product/issues/219
