### ISSUE TITLE
Protocol error: Connection closed. Most likely the page has been closed.

### ISSUE THREAD

**Issue by andrzej-casper** [casper-network/docs#953]
Today I got report from @caspermel that checking external links - `yarn check:externals` - is crashing at the end, without reporting broken URLs:

```
yarn run v1.22.19
$ node check-external-urls.js
Found 168 markdown files. Collecting all external urls...
::group::Found 369 urls within 82 files. Validating URLs...
Progress: 0% (1/369)
Progress: 1% (2/369)
...
...
...
Progress: 99% (367/369)
Progress: 100% (368/369)
Progress: 100% (369/369)
/home/mel/work/github/casper-network/docs-new/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);
              ^
Error: Protocol error: Connection closed. Most likely the page has been closed.
    at assert (/home/mel/work/github/casper-network/docs-new/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at Page.close (/home/mel/work/github/casper-network/docs-new/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2115:32)
    at /home/mel/work/github/casper-network/docs-new/check-external-urls.js:106:24
Node.js v18.14.2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

What is interesting, this issue is not present when running on CI/CD :magic_wand:.

**Comment by andrzej-casper** [comment]
Btw. `evaluateUrl()` is great example of asynchronous JS anti-patterns, and it should be rewritten from scratch.

**Comment by caspermel** [comment]
Fully agree on the unnecessary complexity of evaluateUrl() ; It strikes me as someone who just learned how to do something, and decided to do it that way because reasons.
